apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kangshung/argocd-setup.git
        revision: HEAD
        directories:
          - path: '*'
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      source:
        repoURL: https://github.com/kangshung/argocd-setup.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
